image: node:latest

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$K8S_SECRET_SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - install
  #- test
  - build
  - deploy_production

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

#test:
#    stage: test
#    script:
#        - npm test
#    artifacts:
#        paths:
#            - node_modules/

build:
  stage: build
  script:
    - npm build

deploy_production:
  stage: deploy_production
  only:
    - master
  script:
    # - ssh antoniodiaz@antoniodiaz.me "cd www/antoniodiaz && rm -rf node_modules dist/* && git pull && npm i && npm run build && git checkout master"
