image: node:latest

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git
  - sudo 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - sudo eval $(ssh-agent -s)
  - sudo ssh-add <(echo "$K8S_SECRET_SSH_PRIVATE_KEY" | base64 -d)
  - sudo mkdir -p ~/.ssh
  - sudo '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - install
  - test
  - build_staging
  - build_production
  - deploy_staging
  - deploy_production

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install --verbose
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - node_modules/

build_staging:
  stage: build_staging
  only:
    - staging
  script:
    - npm run stage

build_prod:
  stage: build_production
  only:
    - master
  script:
    - npm run prod

deploy_staging:
  stage: deploy_staging
  only:
    - staging
  script:
    - sudo ssh antoniodiaz@antoniodiaz.me "cd ~/www/linking_frontend_staging && rm -rf node_modules dist/* tmp"
    - sudo ssh antoniodiaz@antoniodiaz.me "cd ~/www/linking_frontend_staging && git pull"
    - sudo ssh antoniodiaz@antoniodiaz.me "source ~/.bash_profile && export NPM_TOKEN=${NPM_TOKEN} && cd ~/www/linking_frontend_staging && nvm use --delete-prefix && git checkout staging && npm ci --verbose && npm run stage"
    - sudo ssh antoniodiaz@antoniodiaz.me "cd ~/www/linking_frontend_staging && mkdir -p tmp/always_restart.txt"

deploy_production:
  stage: deploy_production
  only:
    - master
  script:
    - sudo ssh antoniodiaz@antoniodiaz.me "cd ~/www/linking_frontend_production && rm -rf node_modules dist/* tmp"
    - sudo ssh antoniodiaz@antoniodiaz.me "cd ~/www/linking_frontend_production && git pull"
    - sudo ssh antoniodiaz@antoniodiaz.me "source ~/.bash_profile && export NPM_TOKEN=${NPM_TOKEN} && cd ~/www/linking_frontend_production && nvm use --delete-prefix && git checkout master && npm ci --verbose && npm run prod"
    - sudo ssh antoniodiaz@antoniodiaz.me "cd ~/www/linking_frontend_production && mkdir -p tmp/always_restart.txt"
