image: node:11

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$K8S_SECRET_SSH_PRIVATE_KEY" | base64 -d)
  - ssh-add <(echo "$K8S_SECRET_SSH_PRIVATE_KEY_AWS" | base64 -d)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - install
  - test
  - build_staging
  - build_production
  - deploy_staging
  - deploy_production

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install --verbose -f
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - node_modules/

build_staging:
  stage: build_staging
  only:
    - staging
  script:
    - npm run stage

build_prod:
  stage: build_production
  only:
    - master
  script:
    - npm run prod

deploy_staging:
  stage: deploy_staging
  only:
    - staging
  script:
    - ssh xum35s@ec2-3-120-27-57.eu-central-1.compute.amazonaws.com "cd /var/www/html/urligram/staging.urligram.com && rm -rf node_modules dist/* tmp"
    - ssh xum35s@ec2-3-120-27-57.eu-central-1.compute.amazonaws.com "cd /var/www/html/urligram/staging.urligram.com && git pull origin staging"
    - ssh xum35s@ec2-3-120-27-57.eu-central-1.compute.amazonaws.com "source ~/.bash_profile && export NPM_TOKEN=${NPM_TOKEN} && cd /var/www/html/urligram/staging.urligram.com && nvm use --delete-prefix && git checkout staging && npm ci --verbose && npm run stage"
    - ssh xum35s@ec2-3-120-27-57.eu-central-1.compute.amazonaws.com "cd /var/www/html/urligram/staging.urligram.com && export SECRET=${SECRET} && NODE_ENV=staging pm2 restart ./dist/server.js --name staging.urligram.com --update-env"

deploy_production:
  stage: deploy_production
  only:
    - master
  script:
    - ssh xum35s@ec2-3-120-27-57.eu-central-1.compute.amazonaws.com "cd /var/www/html/urligram/urligram.com && rm -rf node_modules dist/* tmp"
    - ssh xum35s@ec2-3-120-27-57.eu-central-1.compute.amazonaws.com "cd /var/www/html/urligram/urligram.com && git pull origin master"
    - ssh xum35s@ec2-3-120-27-57.eu-central-1.compute.amazonaws.com "source ~/.bash_profile && export NPM_TOKEN=${NPM_TOKEN} && cd /var/www/html/urligram/urligram.com && nvm use --delete-prefix && git checkout master && npm ci --verbose && npm run prod"
    - ssh xum35s@ec2-3-120-27-57.eu-central-1.compute.amazonaws.com "cd /var/www/html/urligram/urligram.com && export SECRET=${SECRET} && NODE_ENV=production pm2 restart ./dist/server.js --name urligram.com --update-env"
