services:
  client:
    env_file:
      - .env
    build:
      target: development-runtime
    environment:
      NODE_ENV: development
      APP_ENV: localDevelopment
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "9228:9228"
